version: '3'

services:
  backend:
    container_name: LEADS2B-BACKEND
    build: .
    env_file: .env
    volumes:
      - .:/backend
      - /backend/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: LEADS2B-DB
    ports:
      - '27017:27017'
    # volumes:
    #   - ./data/db:/data/db
